### ISSUE TITLE
Logo issue

### ISSUE THREAD

**Issue by CheFuls** [GhostTypes/orion#6]
When opening hud ur crashing

Crash string java.lang.NoSuchMethodError: 'void 
meteordevelopment.meteorclient.renderer.GL.bindTexture(net.minecraft.class_2960)

Meteor version 0.4.5 (downloaded from website)
Minecraft version 1.17.1

**Comment by GhostTypes** [comment]
This is already fixed in the latest version. And you should be using meteor dev builds
